### ISSUE TITLE
Documentation not up to date

### ISSUE THREAD

**Issue by nidkil** [nspragg/filesurgeon#3]
Cool module.

It seems that the documentation is not up to date in regards to edit, as edit is not static.

The current edit examples look like this:

```
import FileSurgeon from 'FileSurgeon';

const contents = FileSurgeon.edit(filename)
 .set(1, line)
 .filter(fn)
 .map(fn)
 .preview(); // writes changes to stdout

```

They should be like this:

```
import FileSurgeon from 'FileSurgeon';

const fileSurgeon = new FileSurgeon(filename)
const contents = fileSurgeon.edit()
 .set(1, line)
 .filter(fn)
 .map(fn)
 .preview(); // writes changes to stdout
```

Alternatively the call can be handled as follows:

```
import FileSurgeon from 'FileSurgeon';

const fileSurgeon = FileSurgeon.create(filename)
fileSurgeon
 .edit()
 .set(1, line)
 .filter(fn)
 .map(fn)
 .preview(); // writes changes to stdout
```

As a matter of interest, why is edit the only method that is not static? Why are the other methods static?

**Comment by nidkil** [comment]
As a matter of interest, why is edit the only method that is not static? Why are the other methods static?

**Comment by nspragg** [comment]
@nidkil  - thanks. Documentation has been updated.
