### ISSUE TITLE
Error if file does not exist

### ISSUE THREAD

**Issue by nidkil** [nspragg/filesurgeon#4]
### Description

When using FileSurgeon to create a new file an error is thrown when `.save()` is called.

### Expected behaviour

If the file does not exist it is created.

### Actual behaviour

The following error is thrown:

```
Error: ENOENT: no such file or directory, open 'C:\dev\wtf\vue-msal\dist\index.js'
Emitted 'error' event at:
    at lazyFs.open (internal/fs/streams.js:115:12)
    at FSReqWrap.oncomplete (fs.js:139:20)
```

A temp file is created, but it is empty.

### Steps to reproduce

```
const destPath = 'my-tet-file.txt';
const fileSurgeon = FileSurgeon.create(destPath).edit();
fileSurgeon.append('Line 1');
fileSurgeon.append('Line 2');
fileSurgeon.save();
```

As a workaround I have created an empty file with the following function:

```
function createEmptyFile (filePath) {
  fs.closeSync(fs.openSync(filePath, 'w'))
}
```

If the function is called before `.save()` it works.

I also tried using `.saveAs(destPath)` and it throw the same error.

### Operating system

Windows 10

**Comment by nspragg** [comment]
@nidkil - thanks for raising this issue. The original intention of `edit` was to manipulate existing files. However, creating a new file is a valid use case and I'll happy to add support for this. 

I'll probably address this within the next week.

**Comment by nspragg** [comment]
@nidkil  - An uncaught exception was being thrown for non-existent files. This has now been fixed:

```js
try {
   await FileSurgeon.edit('invalid.txt')
      .append('data')
      .save();
} catch (err) {
  console.error(err);
}
```

The ability to create content for new files has also been added (via `FileSurgeon.new`)
